config/routes.rb
Rails.application.routes.draw do
 resources :jobs

 root 'jobs#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_job, except: [:new, :create, :index]

	def index
		if params[:category].blank?
			@jobs = Job.all.order(created_at: :desc)
		else
			@category_id = Category.find_by(name: params[:category]).id 
			@jobs = Job.where("category_id=?", @category_id).order(created_at: :desc)
		end
	end

	def show
	end

	def edit
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.create(job_params)

		if @job.save
			redirect_to @job, notice: "Saved successfully"
		else
			render 'new'
		end
	end

	def update
		if @job.update_attributes(job_params)
			redirect_to @job
		else
			render 'edit'
		end
	end

	def destroy
		if @job.destroy
			redirect_to root_url, notice: "Job deleted"
		end
	end


	private

	def set_job
		@job = Job.find(params[:id])
	end

	def job_params
		params.require(:job).permit(:title, :description, :company, :url,
			                        :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: {class: 'form-horizontal'}) do |f|
	- if @job.errors.any?
		#errors
			%p
				= pluralize(@job.errors.count, "error")
				Prevented the form from saving
			%ul
				- @job.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}, input_html: {class: "dropdown-toggle"}
		= f.input :title, label: "Job Title"
		= f.input :description, label: "Job Description"
		= f.input :company, label: "Company Name"
		= f.input :url, label: "Job Link"
	%br	
	= f.button :submit, class: "btn btn-primary"

app/views/jobs/edit.html.haml
%h1 Edit a Job

= render 'form'

= link_to "Back", @job

app/views/jobs/index.html.haml
#jobs
	- @jobs.each do |job|
		.job
			%h2= link_to job.title, job_path(job)
			%p= job.company

app/views/jobs/new.html.haml
%h1 New Job

= render 'form'
%br

= link_to "Back", root_url

app/views/jobs/show.html.haml
#jobs
	.job
		%h2= @job.title
		%p= @job.description
		%p= @job.company
		= link_to "Apply for the Job", @job.url, class: "button btn btn-warning"

=link_to "Home", root_url, class: "btn btn-default"
=link_to "Edit", edit_job_path(@job), class: "btn btn-default"
=link_to "Delete", @job, method: :delete, data: {confirm: "Are You sure?"}, class: "btn btn-danger"

app/views/layouts/application.html.haml
!!! 5

%html
%head
	%title Workout App
	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
.nav.navbar.navbar-default
	.container
		.navbar-brand Workout App
		%ul.nav.navbar-nav
			%li= link_to "balala", "#"
		
		= link_to "New Workout", '#', class: "navbar-text navbar-right navbar-link"

	

.container
	= yield